#!/bin/bash
port=`[ $# -eq 0 ] && echo 8800 || [ $# -eq 1 ] && echo $1`
[ $# -gt 1 ] && echo Un solo parámetro como máximo. && exit 1

let v=`python --version | awk '{gsub(/\..*$/, "", $2); print $2}'`

case $v in
    2) python -m SimpleHTTPServer $port ;;
    3) python -m http.server $port --bind 127.0.0.1 ;;
esac
